# frontend/Dockerfile

# Use the official Nginx image as a base
FROM nginx:1.21-alpine

# Copy the frontend files from the build context into the container
COPY ./index.html /usr/share/nginx/html/index.html