# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_api
    restart: unless-stopped
    env_file:
      - ./.env # Pass environment variables from .env file
    networks:
      - app-network

  frontend:
    image: nginx:1.21-alpine
    container_name: frontend_nginx
    restart: unless-stopped
    ports:
      - "80:80" # Expose Nginx on port 80 of the host
    volumes:
      - ./frontend:/usr/share/nginx/html # Mount frontend code
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Mount nginx config
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge