# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_api
    restart: unless-stopped
    env_file:
      - ./.env # Pass environment variables from .env file
    networks:
      - app-network

frontend:
    build: ./frontend  # Tells Docker to build the image from the ./frontend directory
    container_name: frontend_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # We still need the nginx config
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge